export const data = [
  {
    id: 1,
    text: "Review pull requests",
    completed: true,
    assignedTo: "User_4",
  },
  {
    id: 2,
    text: "Prepare budget forecast",
    completed: true,
    assignedTo: "User_5",
  },
  { id: 3, text: "Write documentation", completed: true, assignedTo: "User_1" },
  { id: 4, text: "Finish the report", completed: true, assignedTo: "User_1" },
  { id: 5, text: "Organize workspace", completed: false, assignedTo: "User_4" },
  {
    id: 6,
    text: "Prepare budget forecast",
    completed: false,
    assignedTo: "User_2",
  },
  { id: 7, text: "Test new features", completed: true, assignedTo: "User_5" },
  { id: 8, text: "Finish the report", completed: false, assignedTo: "User_4" },
  { id: 9, text: "Organize workspace", completed: false, assignedTo: "User_4" },
  {
    id: 10,
    text: "Update website content",
    completed: true,
    assignedTo: "User_1",
  },
  {
    id: 11,
    text: "Write documentation",
    completed: true,
    assignedTo: "User_4",
  },
  {
    id: 12,
    text: "Review pull requests",
    completed: true,
    assignedTo: "User_4",
  },
  { id: 13, text: "Plan team outing", completed: false, assignedTo: "User_5" },
  { id: 14, text: "Organize workspace", completed: true, assignedTo: "User_3" },
  {
    id: 15,
    text: "Schedule client meeting",
    completed: false,
    assignedTo: "User_3",
  },
  {
    id: 16,
    text: "Update website content",
    completed: false,
    assignedTo: "User_5",
  },
  {
    id: 17,
    text: "Update the project plan",
    completed: false,
    assignedTo: "User_3",
  },
  { id: 18, text: "Finish the report", completed: true, assignedTo: "User_3" },
  {
    id: 19,
    text: "Review pull requests",
    completed: true,
    assignedTo: "User_5",
  },
  {
    id: 20,
    text: "Meet with stakeholders",
    completed: false,
    assignedTo: "User_3",
  },
];
